############# English navigation ##############

# main menu

[[main]]
name = "Odoo"
url = "/odoo"
weight = 1

[[main]]
name = "Blog"
url = "/blog"
weight = 2

[[main]]
name = "About"
url = "/about"
weight = 3

[[main]]
weight = 4
name = "Services"

[[main]]
parent = "Services"
name = "Ecommerce Consulting"
url = "/404"
pre = "fa-solid fa-cart-shopping"

[[main]]
parent = "Services"
name = "Odoo Support"
url = "/404"
pre = "fa-solid fa-life-ring"

[[main]]
parent = "Services"
name = "Platform Migrations"
url = "/404"
pre = "fa-solid fa-right-left"

[[main]]
parent = "Services"
name = "Automation & AI"
url = "/404"
pre = "fa-solid fa-robot"

[[main]]
parent = "Services"
name = "Business Software Training"
url = "/404"
pre = "fa-solid fa-chalkboard-user"

[[main]]
parent = "Services"
name = "Custom Solutions"
url = "/404"
pre = "fa-solid fa-screwdriver-wrench"


# footer menu
[[footer]]
name = "Odoo"
url = "/odoo"
weight = 1

[[footer]]
name = "About"
url = "/about"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
