############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Odoo"
url = "/odoo"
weight = 2

[[main]]
name = "Blog"
url = "/blog"
weight = 3

[[main]]
name = "About"
url = "/about"
weight = 4

[[main]]
weight = 5
name = "Services"

[[main]]
parent = "Services"
name = "Ecommerce Consulting" 
url = "/404"

[[main]]
parent = "Services"
name = "Odoo Support"
url = "/404"

[[main]]
parent = "Services"
name = "Platform Migrations"
url = "/404"

[[main]]
parent = "Services"
name = "Automation & AI"
url = "/404"

[[main]]
parent = "Services"
name = "Business Software Training"
url = "/404"

[[main]]
parent = "Services"
name = "Custom Solutions"
url = "/404"


# footer menu
[[footer]]
name = "Odoo"
url = "/odoo"
weight = 1

[[footer]]
name = "About"
url = "/about"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
